---
# Wazuh Cluster Deployment Playbook
# Usage: ansible-playbook -i inventory/hosts.ini site.yml

- name: Generate certificates (run locally)
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - role: certificates
      tags: [certs, certificates]

- name: Configure common settings on all Wazuh nodes
  hosts: wazuh
  become: true
  roles:
    - role: common
      tags: [common]

- name: Deploy Wazuh Indexers
  hosts: indexers
  become: true
  serial: 1
  roles:
    - role: indexer
      tags: [indexer, indexers]

- name: Initialize Indexer Security
  hosts: indexers[0]
  become: true
  tasks:
    - name: Wait for indexer cluster to form
      wait_for:
        host: "{{ indexer_1_ip }}"
        port: 9200
        delay: 10
        timeout: 300

    - name: Initialize security plugin
      command: /usr/share/wazuh-indexer/bin/indexer-security-init.sh
      register: security_init
      changed_when: security_init.rc == 0
      failed_when: false
      tags: [indexer, init]

    - name: Verify cluster health
      uri:
        url: "https://localhost:9200/_cluster/health"
        method: GET
        user: "{{ indexer_admin_user }}"
        password: "{{ indexer_admin_password }}"
        validate_certs: false
        return_content: true
      register: cluster_health
      until: cluster_health.json.status in ['green', 'yellow']
      retries: 30
      delay: 10
      tags: [indexer, verify]

    - name: Display cluster health
      debug:
        var: cluster_health.json
      tags: [indexer, verify]

- name: Deploy Wazuh Manager (Master)
  hosts: master
  become: true
  roles:
    - role: manager
      tags: [manager, master]

- name: Deploy Wazuh Dashboard
  hosts: dashboard
  become: true
  roles:
    - role: dashboard
      tags: [dashboard]

- name: Deploy Wazuh Manager (Workers)
  hosts: workers
  become: true
  roles:
    - role: manager
      tags: [manager, workers]

- name: Verify cluster deployment
  hosts: master
  become: true
  tasks:
    - name: Wait for all managers to join cluster
      pause:
        seconds: 30

    - name: Check manager cluster status
      command: /var/ossec/bin/cluster_control -l
      register: cluster_status
      changed_when: false
      tags: [verify]

    - name: Display cluster status
      debug:
        var: cluster_status.stdout_lines
      tags: [verify]

    - name: Deployment summary
      debug:
        msg:
          - "======================================"
          - "   Wazuh Cluster Deployment Complete!"
          - "======================================"
          - ""
          - "Dashboard: https://{{ master_ip }}:443"
          - "Username: admin"
          - "Password: admin (CHANGE THIS!)"
          - ""
          - "SSH Tunnel Command:"
          - "ssh -L 8443:{{ master_ip }}:443 -i ~/.ssh/wazuh-cluster-key ec2-user@BASTION_IP"
          - ""
          - "Then open: https://localhost:8443"
      tags: [verify]
